name: "Performance Report"
description: "Generating Performance report from Browserstack session API"
inputs:
  bs_username:
    description: "username for browserstack auth"
    required: true
  bs_access_key:
    description: "access key for browserstack auth"
    required: true
  bs_session_id:
    description: "session id for test report"
    required: true
  gh_pages:
    description: 'Folder with gh-pages branch'
    required: false
    default: 'gh-pages'
  subfolder:
    description: 'subfolder'
    required: false
    default: 'performance'
  keep_reports:
    description: 'Keep X last reports'
    required: false
    default: '30'
  cpu_threshold:
    description: 'maximum cpu'
    required: false
    default: 50
  github_run_num:
    description: 'GitHub Actions build number'
    required: true
    default: ${{ github.run_number }}
  github_run_id:
    description: 'GitHub Actions run id'
    required: true
    default: ${{ github.run_id }}
  github_repo:
    description: 'GitHub repository'
    required: true
    default: ${{ github.repository }}
  github_repo_owner:
    description: 'GitHub repository owner'
    required: true
    default: ${{ github.repository_owner }}
outputs:
  build:
    description: 'app build used for the test run'
  cpu_max: 
    description: 'cpu exceeded threshold value message'
runs:
  using: "node16"
  main: 'dist/index.js'
